### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by panhs** [JacKMoChen/MyMusic#1]
I/flutter (23150): Request Exception: DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1
I/flutter (23150): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
I/flutter (23150): #1      RequestOptions.uri (package:dio/src/options.dart:301:29)
I/flutter (23150): #2      LogInterceptor.onError (package:dio/src/interceptors/log.dart:81:36)
I/flutter (23150): #3      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:867:40)
I/flutter (23150): #4      _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter (23150): #5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
I/flutter (23150): #6      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
I/flutter (23150): #7      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
I/flutter (23150): #8      Future._propagateToListeners (dart:async/future_impl.dart:713:24)

**Comment by laochen923** [comment]
这个要自己配置API啊

**Comment by laochen923** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi
